module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  roots: ["<rootDir>/apps", "<rootDir>/packages"],
  testMatch: ["**/__tests__/**/*.[jt]s?(x)", "**/?(*.)+(spec|test).[jt]s?(x)"],
  collectCoverageFrom: [
    "apps/**/*.{ts,tsx}",
    "packages/**/*.{ts,tsx}",
    "!apps/**/node_modules/**",
    "!packages/**/node_modules/**",
    "!apps/**/dist/**",
    "!packages/**/dist/**",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov", "html"],
  moduleNameMapper: {
    "^@/(.*)$": "<rootDir>/$1",
    "^@packages/(.*)$": "<rootDir>/packages/$1/src",
    "^@config/(.*)$": "<rootDir>/packages/config/src/$1",
    "^@constants/(.*)$": "<rootDir>/packages/constants/src/$1",
    "^@errors/(.*)$": "<rootDir>/packages/errors/src/$1",
    "^@middlewares/(.*)$": "<rootDir>/packages/middlewares/src/$1",
    "^@validation/(.*)$": "<rootDir>/packages/validation/src/$1",
    "^@responses/(.*)$": "<rootDir>/packages/responses/src/$1",
    "^@swagger/(.*)$": "<rootDir>/packages/swagger/src/$1",
    "^@logger/(.*)$": "<rootDir>/packages/logger/src/$1",
    "^@utils/(.*)$": "<rootDir>/packages/utils/src/$1",
    "^@types/(.*)$": "<rootDir>/packages/types/src/$1",
  },
};
